default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: incubit_development

test:
  <<: *default
  database: incubit_test

production:
  <<: *default
  database: <%= ENV['INCUBIT_DATABASE'] %>
  username: <%= ENV['INCUBIT_DATABASE_USERNAME'] %>
  password: <%= ENV['INCUBIT_DATABASE_PASSWORD'] %>
